import pathlib
lines = []
def L(s): lines.append(s)
L("# Dataset-Build Side Map -- E:\git\beatgen")
L("")
L("Read-only report. All citations are file:line.")
L("")
L("---")
L("")
L("## 1. Top-level structure -- phases of the build pipeline (per song)")
L("")
L("For a single song, the per-song worker (_process_one) runs these phases in this order.")
L("")
L("| Phase | File:Line | Existing console output |")
L("|---|---|---|")
L("| 0. Worker enters task | extract/build_dataset.py:115-119 | _w(f"start {sid}") (debug only) |")
L("| 1. Load level (UnityPy / map folder) | extract/build_dataset.py:122-126 | _w(f"loaded in ...s") (debug only) |")
L("| 2. Normalize difficulties | extract/build_dataset.py:129-131 | _w(f"normalized in ...s") (debug only) |")
L("| 3a. load_mono_22k decode | extract/build_dataset.py:138-139 | _w("load_mono_22k ...") (debug only) |")
L("| 3b. log_mel | extract/build_dataset.py:141-142 | _w(f"mel {mel.shape}") (debug only) |")
L("| 3c. np.save mel | extract/build_dataset.py:143 | _w(f"mel done in ...s") (debug only) |")
L("| 4. Write per-diff json and meta | extract/build_dataset.py:152-156 | _w("done") (debug only) |")
L("| End. Parent _accumulate summary | extract/build_dataset.py:255 | always via _summarise |")
L("")
L("---")
L("")
L("## 2. Per-song entry point")
L("")
L("extract/build_dataset.py:113:")
L("")
L("")
L("")
L("args is a 5-tuple (task, sid, out_root, force, debug) built at extract/build_dataset.py:331.")
L("")
L("task is one of:")
L("- ("bundle", str(bundle_path))")
L("- ("map", (str(folder), info_filename))")
L("")
L("Returns status dict, never raises (outer try/except at build_dataset.py:192-194).")
L("")
p = pathlib.Path(r"C:\Users\metashket\.claude\plans\snuggly-knitting-crane-agent-a7aa105aad1c9c51f.md")
p.write_text("
".join(lines), encoding="utf-8")
print("wrote", len("
".join(lines)), "bytes")
